'use client';

import { useRouter } from 'next/navigation';
import Link from 'next/link';

export default function TermsPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)]">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <button
          onClick={() => router.back()}
          className="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors mb-8 inline-block"
        >
          &larr; Back
        </button>

        <h1 className="text-2xl font-semibold mb-8">Terms and Conditions</h1>

        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed mb-6">
          Last updated: February 2026
        </p>

        {/* 1. Acceptance of Terms */}
        <h2 className="text-lg font-medium mt-8 mb-3">1. Acceptance of Terms</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          By accessing or using this website (<strong className="text-gray-900 dark:text-gray-100">andrey.kovalev.dev</strong>),
          you agree to be bound by these Terms and Conditions. If you do not agree with any
          part of these terms, please do not use this website. Continued use of the site
          constitutes acceptance of any updates or modifications to these terms.
        </p>

        {/* 2. Description of Service */}
        <h2 className="text-lg font-medium mt-8 mb-3">2. Description of Service</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          This website is the personal portfolio of Andrey Kovalev, a software developer
          based in Riga, Latvia. The site showcases professional work, skills, and experience.
          It also features an AI-powered chat assistant that can help visitors navigate the
          portfolio, answer questions about the owner&apos;s background, and interact with
          various sections of the site through a set of built-in tools.
        </p>

        {/* 3. AI Chat Disclaimer */}
        <h2 className="text-lg font-medium mt-8 mb-3">3. AI Chat Disclaimer</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed mb-3">
          The AI chat assistant is provided for informational and navigational purposes only.
          Please be aware of the following:
        </p>
        <ul className="list-disc list-inside text-sm text-gray-600 dark:text-gray-400 leading-relaxed space-y-2 ml-2">
          <li>
            All responses are generated by an artificial intelligence model and may contain
            inaccuracies, outdated information, or errors.
          </li>
          <li>
            The assistant does not provide professional, legal, financial, medical, or any
            other form of certified advice.
          </li>
          <li>
            The AI operates using a third-party language model (such as xAI/Grok or other
            OpenAI-compatible providers). Responses are not manually reviewed or endorsed
            by the site owner.
          </li>
          <li>
            The assistant has access to 22 built-in tools that allow it to navigate the
            portfolio interface on your behalf (e.g., opening panels, switching views,
            displaying projects). These tools only affect your local browsing session and
            do not modify any data.
          </li>
          <li>
            You should not rely on any AI-generated response as a substitute for
            independent research or professional consultation.
          </li>
        </ul>

        {/* 4. Acceptable Use */}
        <h2 className="text-lg font-medium mt-8 mb-3">4. Acceptable Use</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed mb-3">
          When using this website and its AI chat feature, you agree not to:
        </p>
        <ul className="list-disc list-inside text-sm text-gray-600 dark:text-gray-400 leading-relaxed space-y-2 ml-2">
          <li>
            Abuse, harass, or send harmful, offensive, or illegal content through the
            chat interface.
          </li>
          <li>
            Attempt to manipulate, jailbreak, or circumvent the AI assistant&apos;s
            intended behavior, safety guidelines, or system instructions.
          </li>
          <li>
            Use automated scripts, bots, or other programmatic means to access the
            chat or any other part of the website without prior written permission.
          </li>
          <li>
            Interfere with or disrupt the website&apos;s functionality, infrastructure,
            or the experience of other visitors.
          </li>
          <li>
            Attempt to extract, reverse-engineer, or reconstruct the AI&apos;s system
            prompt or internal configuration.
          </li>
        </ul>

        {/* 5. Intellectual Property */}
        <h2 className="text-lg font-medium mt-8 mb-3">5. Intellectual Property</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          All content on this website &mdash; including but not limited to text, images,
          design, code, project descriptions, and portfolio data &mdash; is the intellectual
          property of Andrey Kovalev unless otherwise stated. You may not reproduce,
          distribute, or create derivative works from any content on this site without
          explicit written permission from the owner.
        </p>

        {/* 6. User Content */}
        <h2 className="text-lg font-medium mt-8 mb-3">6. User Content</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          Messages you send through the AI chat assistant may be logged for the purposes
          of improving the service, monitoring abuse, and ensuring the quality of
          interactions. These messages are also transmitted to a third-party AI provider
          for processing. By using the chat, you acknowledge that your messages may be
          stored and processed as described in our{' '}
          <Link
            href="/privacy"
            className="text-gray-900 dark:text-gray-100 underline underline-offset-2"
          >
            Privacy Policy
          </Link>
          . Please do not share sensitive personal information, passwords, or confidential
          data through the chat interface.
        </p>

        {/* 7. Third-Party Services */}
        <h2 className="text-lg font-medium mt-8 mb-3">7. Third-Party Services</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          This website relies on third-party services for its operation, including but
          not limited to AI language model providers (such as xAI, OpenAI, or other
          compatible providers) and hosting platforms. These services have their own
          terms of use and privacy policies. The site owner is not responsible for the
          practices, availability, or content provided by these third-party services.
        </p>

        {/* 8. Limitation of Liability */}
        <h2 className="text-lg font-medium mt-8 mb-3">8. Limitation of Liability</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          This website and all its features, including the AI chat assistant, are
          provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis.
          To the fullest extent permitted by applicable law, Andrey Kovalev shall not
          be liable for any direct, indirect, incidental, special, consequential, or
          punitive damages arising from your use of or inability to use this website,
          including any reliance on information provided by the AI assistant.
        </p>

        {/* 9. No Warranties */}
        <h2 className="text-lg font-medium mt-8 mb-3">9. No Warranties</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          The site owner makes no warranties or representations, express or implied,
          regarding the accuracy, completeness, reliability, or availability of this
          website or any content on it. This includes, without limitation, any implied
          warranties of merchantability, fitness for a particular purpose, or
          non-infringement. The AI chat assistant may experience downtime, errors, or
          produce unexpected results at any time.
        </p>

        {/* 10. Termination */}
        <h2 className="text-lg font-medium mt-8 mb-3">10. Termination</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          The site owner reserves the right to restrict, suspend, or terminate access
          to the website or any of its features &mdash; including the AI chat
          assistant &mdash; at any time, for any reason, without prior notice. This
          may include blocking access for users who violate these terms or engage in
          abusive behavior.
        </p>

        {/* 11. Governing Law */}
        <h2 className="text-lg font-medium mt-8 mb-3">11. Governing Law</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          These Terms and Conditions are governed by and construed in accordance with
          the laws of the Republic of Latvia. Any disputes arising from or related to
          the use of this website shall be subject to the exclusive jurisdiction of the
          courts of the Republic of Latvia.
        </p>

        {/* 12. Changes to Terms */}
        <h2 className="text-lg font-medium mt-8 mb-3">12. Changes to Terms</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          These terms may be updated or modified at any time without prior notice.
          Any changes will be effective immediately upon being posted on this page.
          The &ldquo;Last updated&rdquo; date at the top reflects the most recent
          revision. It is your responsibility to review these terms periodically.
          Continued use of the website after changes constitutes acceptance of the
          revised terms.
        </p>

        {/* 13. Contact */}
        <h2 className="text-lg font-medium mt-8 mb-3">13. Contact</h2>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
          If you have any questions or concerns about these Terms and Conditions,
          please contact:
        </p>
        <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed mt-3">
          Andrey Kovalev<br />
          <a
            href="mailto:g.andry90@gmail.com"
            className="text-gray-900 dark:text-gray-100 underline underline-offset-2"
          >
            g.andry90@gmail.com
          </a><br />
          Riga, Latvia
        </p>

        <div className="mt-12 pt-8 border-t border-gray-200 dark:border-gray-800">
          <p className="text-xs text-gray-400 dark:text-gray-500">
            &copy; {new Date().getFullYear()} Andrey Kovalev. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
